# GitHub Sponsors configuration
# Add your sponsorship options here when ready

# github: [evansinho]
# patreon: lumina
# open_collective: lumina
# ko_fi: lumina
# custom: ['https://lumina.dev/sponsor']